// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To generate this file with your own Firebase project credentials:
/// 1. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
/// 2. Run: `flutterfire configure`
/// 3. The CLI will generate this file with your project credentials
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase project credentials for karriova-9d610
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdCEgXFjNjYqMSFfh6hRYKNDdPjafZd0',
    appId: '1:39908931621:web:6ea02752105073b8c4a7cc',
    messagingSenderId: '39908931621',
    projectId: 'karriova-9d610',
    authDomain: 'karriova-9d610.firebaseapp.com',
    storageBucket: 'karriova-9d610.firebasestorage.app',
    measurementId: 'G-JZ6EN2H0KM',
  );

  // TODO: Register Android app in Firebase Console and add google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdCEgXFjNjYqMSFfh6hRYKNDdPjafZd0',
    appId: '1:39908931621:web:6ea02752105073b8c4a7cc',
    messagingSenderId: '39908931621',
    projectId: 'karriova-9d610',
    storageBucket: 'karriova-9d610.firebasestorage.app',
  );

  // TODO: Register iOS app in Firebase Console and add GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdCEgXFjNjYqMSFfh6hRYKNDdPjafZd0',
    appId: '1:39908931621:web:6ea02752105073b8c4a7cc',
    messagingSenderId: '39908931621',
    projectId: 'karriova-9d610',
    storageBucket: 'karriova-9d610.firebasestorage.app',
    iosBundleId: 'com.karriova.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdCEgXFjNjYqMSFfh6hRYKNDdPjafZd0',
    appId: '1:39908931621:web:6ea02752105073b8c4a7cc',
    messagingSenderId: '39908931621',
    projectId: 'karriova-9d610',
    storageBucket: 'karriova-9d610.firebasestorage.app',
    iosBundleId: 'com.karriova.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvdCEgXFjNjYqMSFfh6hRYKNDdPjafZd0',
    appId: '1:39908931621:web:6ea02752105073b8c4a7cc',
    messagingSenderId: '39908931621',
    projectId: 'karriova-9d610',
    storageBucket: 'karriova-9d610.firebasestorage.app',
  );
}
